import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "salted-caramel",
    name_es: "Caramelo Salado",
    name_en: "Salted Caramel",
    description_es: "Galleta de masa suave con un irresistible relleno de caramelo salado y trocitos de sal marina.",
    description_en: "Soft dough cookie with an irresistible salted caramel filling and sea salt flakes.",
    price: 1800,
    available: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    product_images: [{ id: "1", product_id: "salted-caramel", url: "/images/salted-caramel.jpg", display_order: 0 }],
  },
  {
    id: "pistachio-dream",
    name_es: "Pistachio Dream",
    name_en: "Pistachio Dream",
    description_es: "Galleta con masa de pistacho y relleno de crema de pistacho. El sabor más sofisticado de nuestra colección.",
    description_en: "Pistachio dough cookie with pistachio cream filling. The most sophisticated flavor in our collection.",
    price: 2000,
    available: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    product_images: [{ id: "2", product_id: "pistachio-dream", url: "/images/pistachio-dream.jpg", display_order: 0 }],
  },
  {
    id: "lotus-biscoff",
    name_es: "Lotus Biscoff",
    name_en: "Lotus Biscoff",
    description_es: "Galleta con masa de Biscoff y relleno de crema Lotus. Para los fanáticos de esta icónica galleta belga.",
    description_en: "Biscoff dough cookie with Lotus cream filling. For fans of this iconic Belgian cookie.",
    price: 1900,
    available: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    product_images: [{ id: "3", product_id: "lotus-biscoff", url: "/images/lotus-biscoff.jpg", display_order: 0 }],
  },
  {
    id: "milo-bomb",
    name_es: "Milo Bomb",
    name_en: "Milo Bomb",
    description_es: "Galleta de chocolate con fudge de Milo. Una bomba de sabor chocolatado con la infaltable milo de tu infancia.",
    description_en: "Chocolate cookie with Milo fudge. A chocolate flavor bomb with the nostalgic Milo from your childhood.",
    price: 1800,
    available: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    product_images: [{ id: "4", product_id: "milo-bomb", url: "/images/milo-bomb.jpg", display_order: 0 }],
  },
  {
    id: "red-nutella",
    name_es: "Red Nutella",
    name_en: "Red Nutella",
    description_es: "Galleta de masa roja de terciopelo con corazón de Nutella. El contraste perfecto entre red velvet y avellanas.",
    description_en: "Red velvet dough cookie with Nutella heart. The perfect contrast between red velvet dough and hazelnut filling.",
    price: 1900,
    available: true,
    display_order: 5,
    created_at: new Date().toISOString(),
    product_images: [{ id: "5", product_id: "red-nutella", url: "/images/red-nutella.jpg", display_order: 0 }],
  },
  {
    id: "lemon-bliss",
    name_es: "Lemon Bliss",
    name_en: "Lemon Bliss",
    description_es: "Galleta cítrica de limón con crema de limón y ralladura fresca. Fresca, vibrante y equilibrada.",
    description_en: "Citrus lemon cookie with lemon cream and fresh zest. Fresh, vibrant and balanced.",
    price: 1700,
    available: true,
    display_order: 6,
    created_at: new Date().toISOString(),
    product_images: [{ id: "6", product_id: "lemon-bliss", url: "/images/lemon-bliss.jpg", display_order: 0 }],
  },
  {
    id: "red-velvet",
    name_es: "Red Velvet Cookies and Cream",
    name_en: "Red Velvet Cookies and Cream",
    description_es: "Galleta de red velvet con relleno de crema Oreo y cookies trituradas. Una combinación irresistible.",
    description_en: "Red velvet cookie with Oreo cream filling and crushed cookies. An irresistible combination.",
    price: 1900,
    available: true,
    display_order: 7,
    created_at: new Date().toISOString(),
    product_images: [{ id: "7", product_id: "red-velvet", url: "/images/red-velvet.jpg", display_order: 0 }],
  },
  {
    id: "oreo-cookies-cream",
    name_es: "Oreo Cookies and Cream",
    name_en: "Oreo Cookies and Cream",
    description_es: "Galleta de chocolate con crema de Oreo y trocitos de Oreo en la masa. El sabor clásico favorito.",
    description_en: "Chocolate cookie with Oreo cream and Oreo chunks in the dough. Everyone's classic favorite.",
    price: 1800,
    available: true,
    display_order: 8,
    created_at: new Date().toISOString(),
    product_images: [{ id: "8", product_id: "oreo-cookies-cream", url: "/images/oreo-cookies-cream.jpg", display_order: 0 }],
  },
  {
    id: "chocolate-chips",
    name_es: "Chocolate Chips",
    name_en: "Chocolate Chips",
    description_es: "La clásica galleta de chips de chocolate en su máxima expresión. Masa suave por dentro, crujiente por fuera.",
    description_en: "The classic chocolate chip cookie at its finest. Soft inside, slightly crispy outside.",
    price: 1600,
    available: true,
    display_order: 9,
    created_at: new Date().toISOString(),
    product_images: [{ id: "9", product_id: "chocolate-chips", url: "/images/chocolate-chips.jpg", display_order: 0 }],
  },
  {
    id: "klim-brigadeiro",
    name_es: "Klim Brigadeiro",
    name_en: "Klim Brigadeiro",
    description_es: "Galleta inspirada en el brigadeiro brasileño con leche Klim. Dulce, cremosa e irresistiblemente adictiva.",
    description_en: "Cookie inspired by the Brazilian brigadeiro with Klim milk powder. Sweet, creamy and addictive.",
    price: 1900,
    available: true,
    display_order: 10,
    created_at: new Date().toISOString(),
    product_images: [{ id: "10", product_id: "klim-brigadeiro", url: "/images/klim-brigadeiro.jpg", display_order: 0 }],
  },
];
