import type { Product, Category } from "./types";

const now = new Date().toISOString();

function img(id: string, filename: string) {
  return [{ id: `${id}-img`, product_id: id, url: `/images/${filename}`, display_order: 0 }];
}

function p(
  id: string,
  category: Category,
  order: number,
  name_es: string,
  name_en: string,
  price: number,
  description_es: string,
  description_en: string,
  imageFile?: string,
  available: boolean = true,
): Product {
  return {
    id,
    category,
    name_es,
    name_en,
    description_es,
    description_en,
    price,
    available,
    display_order: order,
    created_at: now,
    product_images: imageFile ? img(id, imageFile) : [],
  };
}

export const mockProducts: Product[] = [
  // ─── Galletas ───────────────────────────────────────────────
  p("salted-caramel", "galletas", 1, "Caramelo Salado", "Salted Caramel", 1800,
    "Galleta de masa suave con un relleno irresistible de caramelo salado y trocitos de sal marina.",
    "Soft dough cookie with an irresistible salted caramel filling and sea salt flakes.",
    "salted-caramel.jpg"),
  p("pistachio-dream", "galletas", 2, "Pistachio Dream", "Pistachio Dream", 2000,
    "Galleta con masa de pistacho y relleno de crema de pistacho. El sabor más sofisticado de la colección.",
    "Pistachio dough cookie with pistachio cream filling. The most sophisticated flavor in our collection.",
    "pistachio-dream.jpg"),
  p("lotus-biscoff", "galletas", 3, "Lotus Biscoff", "Lotus Biscoff", 1900,
    "Galleta con masa de Biscoff y relleno de crema Lotus. Para los fanáticos de la icónica galleta belga.",
    "Biscoff dough cookie with Lotus cream filling. For fans of the iconic Belgian cookie.",
    "lotus-biscoff.jpg"),
  p("milo-bomb", "galletas", 4, "Milo Bomb", "Milo Bomb", 1800,
    "Galleta de chocolate con fudge de Milo. Una bomba de chocolate con el Milo de toda la vida.",
    "Chocolate cookie with Milo fudge. A chocolate flavor bomb with the nostalgic Milo of childhood.",
    "milo-bomb.jpg"),
  p("red-nutella", "galletas", 5, "Red Nutella", "Red Nutella", 1900,
    "Galleta de masa red velvet con corazón de Nutella. Contraste perfecto entre el bizcocho rojo y la avellana.",
    "Red velvet dough cookie with a Nutella heart. Perfect contrast between red velvet and hazelnut.",
    "red-nutella.jpg"),
  p("lemon-bliss", "galletas", 6, "Lemon Bliss", "Lemon Bliss", 1700,
    "Galleta cítrica de limón con crema de limón y ralladura fresca. Fresca, vibrante y equilibrada.",
    "Citrus lemon cookie with lemon cream and fresh zest. Fresh, vibrant and balanced.",
    "lemon-bliss.jpg"),
  p("red-velvet", "galletas", 7, "Red Velvet Cookies and Cream", "Red Velvet Cookies and Cream", 1900,
    "Galleta red velvet con relleno de crema Oreo y galletas trituradas. Una combinación irresistible.",
    "Red velvet cookie with Oreo cream filling and crushed cookies. An irresistible combination.",
    "red-velvet.jpg"),
  p("oreo-cookies-cream", "galletas", 8, "Oreo Cookies and Cream", "Oreo Cookies and Cream", 1800,
    "Galleta de chocolate con crema de Oreo y trocitos de Oreo en la masa. El clásico favorito de todos.",
    "Chocolate cookie with Oreo cream and Oreo chunks in the dough. Everyone's classic favorite.",
    "oreo-cookies-cream.jpg"),
  p("chocolate-chips", "galletas", 9, "Chocolate Chips", "Chocolate Chips", 1600,
    "La clásica galleta de chips de chocolate en su mejor versión. Suave por dentro, crujiente por fuera.",
    "The classic chocolate chip cookie at its finest. Soft inside, slightly crispy outside.",
    "chocolate-chips.jpg"),
  p("klim-brigadeiro", "galletas", 10, "Klim Brigadeiro", "Klim Brigadeiro", 1900,
    "Galleta inspirada en el brigadeiro brasileño con leche Klim. Dulce, cremosa y adictiva.",
    "Cookie inspired by the Brazilian brigadeiro with Klim milk powder. Sweet, creamy and addictive.",
    "klim-brigadeiro.jpg"),
  p("thin-cookie", "galletas", 11, "Thin Cookie", "Thin Cookie", 0,
    "Galleta delgada de chip de chocolate con borde crocante, centro suave y sal Maldon.",
    "Thin chocolate chip cookie with a crispy edge, soft center and Maldon salt."),

  // ─── Cajas ──────────────────────────────────────────────────
  p("caja-3-galletas", "cajas", 1, "Caja 3 galletas", "Box of 3 cookies", 40000,
    "Caja de 3 galletas con sabores a elección. +$3.000 por sabor premium (pistacho, Lotus Biscoff).",
    "Box of 3 cookies, flavors of your choice. +$3,000 per premium flavor (pistachio, Lotus Biscoff)."),
  p("caja-5-galletas", "cajas", 2, "Caja 5 galletas", "Box of 5 cookies", 65000,
    "Caja de 5 galletas con sabores a elección. +$3.000 por sabor premium.",
    "Box of 5 cookies, flavors of your choice. +$3,000 per premium flavor."),
  p("caja-6-galletas", "cajas", 3, "Caja 6 galletas", "Box of 6 cookies", 75000,
    "Caja de 6 galletas con sabores a elección. +$3.000 por sabor premium.",
    "Box of 6 cookies, flavors of your choice. +$3,000 per premium flavor."),
  p("caja-4-thin-cookie", "cajas", 4, "Caja x4 Thin Cookie", "Box of 4 Thin Cookies", 31000,
    "Caja de 4 thin cookies.",
    "Box of 4 thin cookies."),

  // ─── Helados ────────────────────────────────────────────────
  p("helado-vaso", "helados", 1, "Helado en vaso", "Ice cream cup", 12500,
    "Helado servido en vaso. +$3.500 por adición de salsa (pistacho, Kinder, Biscoff, Nutella o caramelo).",
    "Ice cream served in a cup. +$3,500 per sauce add-on (pistachio, Kinder, Biscoff, Nutella or caramel)."),
  p("helado-cono", "helados", 2, "Helado en cono", "Ice cream cone", 8500,
    "Helado servido en cono. +$3.500 por adición de salsa.",
    "Ice cream served in a cone. +$3,500 per sauce add-on."),
  p("affogato", "helados", 3, "Affogato", "Affogato", 16000,
    "Helado de vainilla bañado con espresso caliente.",
    "Vanilla ice cream topped with hot espresso."),
  p("combo-helado-galleta-topping", "helados", 4, "Helado + galleta + topping", "Ice cream + cookie + topping", 29500,
    "Combo de helado, galleta y topping. +$3.000 por sabor premium de galleta.",
    "Combo of ice cream, cookie and topping. +$3,000 per premium cookie flavor."),
  p("combo-helado-galleta", "helados", 5, "Helado + galleta", "Ice cream + cookie", 25500,
    "Combo de helado y galleta. +$3.000 por sabor premium de galleta.",
    "Combo of ice cream and cookie. +$3,000 per premium cookie flavor."),

  // ─── Especiales ─────────────────────────────────────────────
  p("cinnamon-roll", "especiales", 1, "Cinnamon Roll", "Cinnamon Roll", 15000,
    "Rollo suave de canela cubierto con frosting de queso crema.",
    "Soft cinnamon roll topped with cream cheese frosting."),
  p("brownie-milo", "especiales", 2, "Brownie Melcochudo de Milo", "Milo Fudge Brownie", 0,
    "Brownie melcochudo con sabor a Milo.",
    "Fudgy brownie with Milo flavor."),
  p("crunchy-brownie", "especiales", 3, "Crunchy Brownie", "Crunchy Brownie", 15900,
    "Brownie de Milo súper melcochudo con capa crocante de chocolate.",
    "Extra-fudgy Milo brownie with a crunchy chocolate layer."),

  // ─── Malteadas ──────────────────────────────────────────────
  p("malteada-caramelo-salado", "malteadas", 1, "Malteada Caramelo Salado", "Salted Caramel Shake", 26900,
    "Malteada con helado de vainilla, salsa de caramelo y trozos de galleta de caramelo salado.",
    "Shake with vanilla ice cream, caramel sauce and salted caramel cookie chunks."),
  p("malteada-chocolate-chip", "malteadas", 2, "Malteada Chocolate Chip", "Chocolate Chip Shake", 26900,
    "Malteada con helado de vainilla, salsa de chocolate y trozos de galleta chocolate chips.",
    "Shake with vanilla ice cream, chocolate sauce and chocolate chip cookie chunks."),
  p("malteada-red-velvet-nutella", "malteadas", 3, "Malteada Red Velvet Nutella", "Red Velvet Nutella Shake", 26900,
    "Malteada con helado de vainilla, salsa de chocolate y trozos de galleta red velvet Nutella.",
    "Shake with vanilla ice cream, chocolate sauce and red velvet Nutella cookie chunks."),
  p("malteada-milo-bomb", "malteadas", 4, "Malteada Milo Bomb", "Milo Bomb Shake", 26900,
    "Malteada con helado de vainilla, salsa de Milo y trozos de galleta Milo Bomb.",
    "Shake with vanilla ice cream, Milo sauce and Milo Bomb cookie chunks."),
  p("malteada-lemon-bliss", "malteadas", 5, "Malteada Lemon Bliss", "Lemon Bliss Shake", 26900,
    "Malteada con helado de vainilla y trozos de galleta de limón.",
    "Shake with vanilla ice cream and lemon cookie chunks."),
  p("malteada-oreo", "malteadas", 6, "Malteada Oreo Cookies and Cream", "Oreo Cookies and Cream Shake", 26900,
    "Malteada con helado de vainilla, salsa de chocolate y trozos de galleta Oreo cookies and cream.",
    "Shake with vanilla ice cream, chocolate sauce and Oreo cookies and cream cookie chunks."),
  p("malteada-klim-brigadeiro", "malteadas", 7, "Malteada Klim Brigadeiro", "Klim Brigadeiro Shake", 26900,
    "Malteada con helado de vainilla y trozos de galleta Klim Brigadeiro.",
    "Shake with vanilla ice cream and Klim Brigadeiro cookie chunks."),
  p("malteada-red-cookies-cream", "malteadas", 8, "Malteada Red Cookies and Cream", "Red Cookies and Cream Shake", 26900,
    "Malteada con helado de vainilla, salsa de chocolate y trozos de galleta red velvet cookies and cream.",
    "Shake with vanilla ice cream, chocolate sauce and red velvet cookies and cream cookie chunks."),
  p("malteada-pistachio-dream", "malteadas", 9, "Malteada Pistachio Dream", "Pistachio Dream Shake", 29900,
    "Malteada con helado de vainilla, salsa de pistacho y trozos de galleta Pistachio Dream.",
    "Shake with vanilla ice cream, pistachio sauce and Pistachio Dream cookie chunks."),
  p("malteada-lotus-biscoff", "malteadas", 10, "Malteada Lotus Biscoff", "Lotus Biscoff Shake", 29900,
    "Malteada con helado de vainilla, salsa de Lotus Biscoff y trozos de galleta Lotus Biscoff.",
    "Shake with vanilla ice cream, Lotus Biscoff sauce and Lotus Biscoff cookie chunks."),

  // ─── Bebidas frías ──────────────────────────────────────────
  p("milo-frio", "bebidas-frias", 1, "Milo", "Milo", 0, "Bebida fría de Milo.", "Cold Milo drink."),
  p("chai-latte-frio", "bebidas-frias", 2, "Chai latte frío", "Iced chai latte", 0, "Chai latte servido frío.", "Iced chai latte."),
  p("matcha-latte", "bebidas-frias", 3, "Matcha latte", "Matcha latte", 0, "Matcha latte frío.", "Iced matcha latte."),
  p("strawberry-matcha", "bebidas-frias", 4, "Strawberry matcha", "Strawberry matcha", 0, "Matcha con fresa.", "Strawberry matcha."),
  p("pistachio-matcha-latte", "bebidas-frias", 5, "Pistachio matcha latte", "Pistachio matcha latte", 0, "Matcha latte con pistacho.", "Pistachio matcha latte."),
  p("frappuccino", "bebidas-frias", 6, "Frappuccino", "Frappuccino", 0, "Bebida de café frappé.", "Blended coffee drink."),
  p("agua", "bebidas-frias", 7, "Agua", "Water", 0, "Agua embotellada.", "Bottled water."),
  p("gaseosa", "bebidas-frias", 8, "Gaseosa", "Soda", 0, "Gaseosa.", "Soft drink."),
  p("leche", "bebidas-frias", 9, "Leche", "Milk", 0, "Leche fría.", "Cold milk."),

  // ─── Bebidas calientes ──────────────────────────────────────
  p("hot-chocolate", "bebidas-calientes", 1, "Hot chocolate", "Hot chocolate", 0, "Chocolate caliente.", "Hot chocolate."),
  p("cappuccino-latte", "bebidas-calientes", 2, "Cappuccino / Latte", "Cappuccino / Latte", 0, "Cappuccino o latte.", "Cappuccino or latte."),
  p("macchiato", "bebidas-calientes", 3, "Macchiato", "Macchiato", 0, "Espresso macchiato.", "Espresso macchiato."),
  p("americano", "bebidas-calientes", 4, "Americano", "Americano", 0, "Café americano.", "Americano coffee."),
  p("espresso", "bebidas-calientes", 5, "Espresso", "Espresso", 0, "Espresso simple.", "Single espresso."),
  p("doble-espresso", "bebidas-calientes", 6, "Doble espresso", "Double espresso", 0, "Espresso doble.", "Double espresso."),
  p("chai-latte", "bebidas-calientes", 7, "Chai latte", "Chai latte", 0, "Chai latte caliente.", "Hot chai latte."),
];

export const mockMerch: Product[] = [
  p("camiseta-1", "galletas", 1, "Camiseta 1", "T-shirt 1", 0, "Camiseta Crooki — diseño 1.", "Crooki T-shirt — design 1."),
  p("camiseta-2", "galletas", 2, "Camiseta 2", "T-shirt 2", 0, "Camiseta Crooki — diseño 2.", "Crooki T-shirt — design 2."),
  p("tote-bag", "galletas", 3, "Tote bag", "Tote bag", 34900, "Tote bag Crooki.", "Crooki tote bag."),
  p("gorra", "galletas", 4, "Gorra", "Cap", 69900, "Gorra Crooki.", "Crooki cap."),
];
